services:
  app:
    build: .
    restart: always
    command: ["/opt/app/.venv/bin/litestar", "run", "--port=8080", "--host=0.0.0.0", "-d"]
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_SESSION=session
      - S3_URL=storage
      - S3_ACCESS_KEY=root
      - S3_SECRET_KEY=password
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      storage:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./bot.session:/opt/app/bot.session
  db:
    image: docker.io/postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -U postgres
  redis:
    image: docker.io/redis:7-alpine
    restart: always
  storage:
    image: docker.io/minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
